services:
  neo4j:
    image: neo4j:5.17
    container_name: nutriscore-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme}"
      NEO4J_dbms_security_auth__minimum__password__length: 8
      NEO4J_dbms_security_auth__require__local__auth: "false"
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-a", "bolt://localhost:7687", "-u", "${NEO4J_USER:-neo4j}", "-p", "${NEO4J_PASSWORD:-changeme}", "RETURN 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  mcp-cypher:
    image: ghcr.io/modelcontextprotocol/neo4j-cypher-mcp:latest
    container_name: nutriscore-mcp-cypher
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 8000
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: "${NEO4J_USER:-neo4j}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD:-changeme}"
      NEO4J_DATABASE: "${NEO4J_DB:-neo4j}"
    ports:
      - "${MCP_CYPHER_PORT:-8000}:8000"

  mcp-memory:
    image: ghcr.io/modelcontextprotocol/neo4j-memory-mcp:latest
    container_name: nutriscore-mcp-memory
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 8000
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: "${NEO4J_USER:-neo4j}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD:-changeme}"
      NEO4J_DATABASE: "${NEO4J_DB:-neo4j}"
    ports:
      - "${MCP_MEMORY_PORT:-8001}:8000"

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-plugins:
